# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-12 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='na', max_length=200),
            preserve_default=False,
        ),
    ]
