# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-11 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.EmailField(max_length=254),
        ),
    ]
