# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-11 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170911_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='email',
        ),
    ]
